services:
    traefik:
        image: "traefik:v2.5"
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:3001"
        ports:
            - "3001:3001"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ../..:/var/www/app
        environment:
            - SOCKETIO_ADMIN_USERNAME=admin
            - SOCKETIO_ADMIN_PASSWORD=$$2a$$12$$qP4IjY2iFzSsC5sMfIcVduc8rhlwZxzw8.xm9/kGlEq4Z1M50E39C
        command: npm run dev:start
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.rrox.rule=PathPrefix(`/`)"
            - "traefik.http.routers.rrox.entrypoints=web"
            - traefik.http.services.rrox.loadBalancer.sticky.cookie.name=rrox_id
            - traefik.http.services.rrox.loadBalancer.sticky.cookie.httpOnly=true
