name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
        
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup node-gyp
        run: npm install -g node-gyp && node-gyp install
        
      - name: Setup Wix Toolset
        run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
        shell: bash
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 1000000

      - name: Build packages & plugins
        run: yarn lerna run build

      - name: Save Electron Build
        uses: actions/upload-artifact@v3
        with:
          name: electron-build
          path: packages/electron/out