name: Build
on: [push, pull_request]

jobs:
  build_for_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.3.0
      with:
        node-version: 14
    - name: install dependencies
      run: yarn install
    - name: build
      run: yarn make
